SELECT 
    P.MEMBER_NAME
    , R.REVIEW_TEXT
    , DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') REVIEW_DATE
FROM
    MEMBER_PROFILE P
    , REST_REVIEW R
    , (
        SELECT MEMBER_ID, COUNT(*)
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY 2 DESC
        LIMIT 1
    ) MOST
WHERE 
    P.MEMBER_ID = R.MEMBER_ID
    AND P.MEMBER_ID = MOST.MEMBER_ID
ORDER BY
    3 ASC,
    2 ASC
;
