SELECT 
    YEAR(S.SALES_DATE) YEAR
    , MONTH(S.SALES_DATE) MONTH
    , U.GENDER GENDER
    , COUNT(DISTINCT U.USER_ID) USERS
FROM 
    ONLINE_SALE S
    , USER_INFO U
WHERE 
    S.USER_ID = U.USER_ID
    AND GENDER IS NOT NULL
GROUP BY 
    YEAR(S.SALES_DATE)
    , MONTH(S.SALES_DATE)
    , U.GENDER
ORDER BY 1, 2, 3
;
