SELECT 
    CAR_ID
    , CASE WHEN CAR_ID in ( 
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE date('20221016') BETWEEN START_DATE and END_DATE
    ) THEN '대여중'
    ELSE '대여 가능'
    END 'AVAILABIlITY'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC
;
