SELECT *
FROM (
    SELECT 
        CAR_ID
        , ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1),1) DIFF
    FROM 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY 
        CAR_ID
) T
WHERE 
    DIFF >= 7
ORDER BY 2 DESC, 1 DESC
;

-- MySQL
-- SELECT 
--     CAR_ID
--     , ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1),1) DIFF
-- FROM 
--     CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- GROUP BY 
--     CAR_ID
-- HAVING 
--     DIFF >= 7
-- ORDER BY 2 DESC, 1 DESC
-- ;
